// Post-build packaging steps:
// 1. drop the intermediate per-module declarations (already bundled into
//    dist/trianglify.d.ts by rollup-plugin-dts)
// 2. generate CJS declarations (trianglify.d.cts) — the package is
//    "type": "module", so plain .d.ts is interpreted as ESM types. The CJS
//    runtime shape is a callable `module.exports = trianglify` (plus a
//    `default` self-reference), which needs `export =` declarations under
//    node16/nodenext resolution, not `export default`.
// 3. emit a minimal declaration for the worker bundle so TS consumers can
//    reference the trianglify/worker specifier without errors
import { rmSync, readFileSync, writeFileSync } from 'node:fs'

rmSync('dist/types', { recursive: true, force: true })

const dts = readFileSync('dist/trianglify.d.ts', 'utf8')
// Collect every `export type { ... }` statement (rollup-plugin-dts may emit
// one or several, single- or multi-line) and resolve `X as Y` aliases to the
// exported name. Fail loudly rather than emit an incomplete .d.cts — this
// runs on the publish path.
const typeExportMatches = [...dts.matchAll(/^export type \{([^}]+)\}/gm)]
if (typeExportMatches.length === 0) {
  throw new Error('postbuild: could not find any `export type { ... }` statement in dist/trianglify.d.ts')
}
const typeNames = [...new Set(
  typeExportMatches
    .flatMap(m => m[1].split(','))
    .map(s => s.trim().split(/\s+as\s+/).pop().trim())
    .filter(Boolean)
)]
if (typeNames.length === 0) {
  throw new Error('postbuild: the type re-export statements in dist/trianglify.d.ts contained no names')
}

const dcts = [
  '// Generated by scripts/postbuild.mjs — CJS view of trianglify.d.ts.',
  '// The type-only namespace merged into the callable export keeps the',
  '// named type exports available to require() consumers.',
  "import type _default from './trianglify.js' with { 'resolution-mode': 'import' }",
  `import type { ${typeNames.map(n => `${n} as _${n}`).join(', ')} } from './trianglify.js' with { 'resolution-mode': 'import' }`,
  'type _defaultType = typeof _default',
  '// the interface ties the recursive knot: module.exports.default === module.exports',
  'interface TrianglifyExport extends _defaultType {',
  '  default: TrianglifyExport',
  '}',
  'declare const trianglify: TrianglifyExport',
  'declare namespace trianglify {',
  ...typeNames.map(n => `  export type ${n} = _${n}`),
  '}',
  'export = trianglify',
  ''
].join('\n')
writeFileSync('dist/trianglify.d.cts', dcts)

writeFileSync(
  'dist/trianglify.worker.d.ts',
  '// dist/trianglify.worker.js is a classic-worker script intended for\n' +
  '// new Worker(...) / TrianglifyWorker — it is not an importable module\n' +
  '// and has no exports.\n' +
  'export {}\n'
)
