name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
    - uses: actions/checkout@v6
    - name: Install pnpm
      uses: pnpm/action-setup@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm install --frozen-lockfile # install dependencies in cleanroom
    - run: pnpm run ci # run the "ci" script defined in package.json
